### ISSUE TITLE
Plugin Failed when default python is python3

### ISSUE THREAD

**Issue by ppwwyyxx** [tristen/vim-sparkup#5]
I use ArchLinux, the default python is python3.
When using sparkup, the python code will throw syntax error.
If I change the first line of ftplugin/html/sparkup.py to ``#!/usr/bin/env python2``, everything will be ok.

I suggest using ``/usr/bin/env python2`` by default, because this works on every system.

**Comment by luchaoo7** [comment]
Hello, I am having the same problem and updated the file. I still get the same error and I think is because python 2 doesn't use parenthesis were as the python 3 does.
